import type { Vendor } from './types';

export const vendors: Vendor[] = [
  {
    id: 'quark_solar',
    name: 'Quark Solar',
    type: 'Product',
    description: 'Advanced solar panel manufacturing and installation services for commercial and industrial clients.',
    solutions: ['energy_management'],
    targetIndustries: ['manufacturing', 'real_estate', 'it_datacenter', 'education'],
    targetRegions: ['IN', 'AE'],
    contact: { email: 'info@quarksolar.com', phone: '+91-9876543210' },
    website: 'https://quarksolar.com',
    rating: 4.7,
    certifications: ['ISO 14001', 'BIS Certified'],
  },
  {
    id: 'breathe_esg',
    name: 'Breathe ESG',
    type: 'Service',
    description: 'End-to-end ESG compliance, carbon accounting, and sustainability reporting platform.',
    solutions: ['esg_analytics'],
    targetIndustries: ['finance', 'it_datacenter', 'manufacturing', 'real_estate'],
    targetRegions: ['IN', 'US', 'EU', 'AE'],
    contact: { email: 'hello@breatheesg.com', phone: '+91-9123456789' },
    website: 'https://breatheesg.com',
    rating: 4.8,
    certifications: ['ISO 27001', 'SOC 2'],
  },
  {
    id: 'furaat',
    name: 'Furaat Water Solutions',
    type: 'Product',
    description: 'Industrial wastewater treatment and water recycling systems for large-scale manufacturing operations.',
    solutions: ['water_treatment'],
    targetIndustries: ['manufacturing', 'steel', 'cement', 'healthcare'],
    targetRegions: ['IN', 'AE'],
    contact: { email: 'contact@furaat.in', phone: '+91-8765432109' },
    website: 'https://furaat.in',
    rating: 4.5,
    certifications: ['ISO 14001', 'CPCB Certified'],
  },
  {
    id: 'plastic_fischer',
    name: 'Plastic Fischer',
    type: 'Service',
    description: 'River plastic collection and recycling solutions preventing ocean pollution at scale.',
    solutions: ['waste_management'],
    targetIndustries: ['manufacturing', 'real_estate', 'logistics'],
    targetRegions: ['IN', 'EU'],
    contact: { email: 'info@plasticfischer.com', phone: '+49-1234567890' },
    website: 'https://plasticfischer.com',
    rating: 4.6,
    certifications: ['B Corp', 'Plastic Neutral Certified'],
  },
  {
    id: 'snowkap',
    name: 'Snowkap',
    type: 'Service',
    description: 'AI-powered ESG analytics platform for comprehensive emissions tracking and regulatory compliance.',
    solutions: ['esg_analytics'],
    targetIndustries: ['finance', 'manufacturing', 'logistics', 'it_datacenter'],
    targetRegions: ['IN', 'US', 'EU'],
    contact: { email: 'hello@snowkap.com', phone: '+91-7654321098' },
    website: 'https://snowkap.com',
    rating: 4.4,
    certifications: ['ISO 27001'],
  },
  {
    id: 'radiance_energy',
    name: 'Radiance Renewable Energy',
    type: 'Product',
    description: 'Complete solar energy solutions including rooftop installations, ground-mounted systems, and energy storage.',
    solutions: ['energy_management'],
    targetIndustries: ['manufacturing', 'real_estate', 'education', 'healthcare'],
    targetRegions: ['IN'],
    contact: { email: 'info@radianceenergy.in', phone: '+91-6543210987' },
    website: 'https://radianceenergy.in',
    rating: 4.3,
    certifications: ['MNRE Approved', 'ISO 14001'],
  },
  {
    id: 'advent_envirotech',
    name: 'Advent Envirotech',
    type: 'Service',
    description: 'Environmental consulting and waste management solutions for industrial clients.',
    solutions: ['waste_management'],
    targetIndustries: ['manufacturing', 'cement', 'steel', 'automotive'],
    targetRegions: ['IN'],
    contact: { email: 'info@adventenvirotech.com', phone: '+91-5432109876' },
    website: 'https://adventenvirotech.com',
    rating: 4.2,
    certifications: ['ISO 14001'],
  },
  {
    id: 'smart_building_automation',
    name: 'Smart Building Automation',
    type: 'Product',
    description: 'IoT-based building management systems for energy efficiency, HVAC control, and occupancy optimization.',
    solutions: ['building_automation'],
    targetIndustries: ['real_estate', 'education', 'healthcare', 'finance'],
    targetRegions: ['IN', 'AE'],
    contact: { email: 'sales@smartba.in', phone: '+91-4321098765' },
    website: 'https://smartba.in',
    rating: 4.5,
    certifications: ['IGBC Partner', 'ISO 14001'],
  },
  {
    id: 'green_fleet_solutions',
    name: 'Green Fleet Solutions',
    type: 'Service',
    description: 'Complete EV fleet transition services including vehicle procurement, charging infra, and fleet analytics.',
    solutions: ['ev_fleet_management'],
    targetIndustries: ['logistics', 'automotive', 'healthcare'],
    targetRegions: ['IN', 'US'],
    contact: { email: 'info@greenfleet.in', phone: '+91-3210987654' },
    website: 'https://greenfleet.in',
    rating: 4.1,
    certifications: ['EV Ready Certified'],
  },
  {
    id: 'aqverium',
    name: 'Aqverium Water Tech',
    type: 'Product',
    description: 'Digital water quality monitoring and predictive maintenance for water treatment plants.',
    solutions: ['water_treatment'],
    targetIndustries: ['manufacturing', 'real_estate', 'cement'],
    targetRegions: ['IN', 'EU'],
    contact: { email: 'contact@aqverium.com', phone: '+91-2109876543' },
    website: 'https://aqverium.com',
    rating: 4.6,
    certifications: ['ISO 14001', 'CE Marked'],
  },
  {
    id: 'causal_dynamics',
    name: 'Causal Dynamics',
    type: 'Service',
    description: 'Advanced climate scenario analysis and risk modelling tools for corporate strategy teams.',
    solutions: ['esg_analytics'],
    targetIndustries: ['finance', 'manufacturing', 'real_estate'],
    targetRegions: ['US', 'EU'],
    contact: { email: 'info@causaldynamics.com', phone: '+1-5551234567' },
    website: 'https://causaldynamics.com',
    rating: 4.7,
    certifications: ['SOC 2 Type II'],
  },
  {
    id: 'biofuture_additives',
    name: 'Biofuture Additives',
    type: 'Product',
    description: 'Bio-based fuel additives that reduce emissions from diesel engines by up to 15%.',
    solutions: ['energy_management'],
    targetIndustries: ['logistics', 'automotive', 'manufacturing'],
    targetRegions: ['IN', 'AE'],
    contact: { email: 'sales@biofuture.in', phone: '+91-1098765432' },
    website: 'https://biofuture.in',
    rating: 4.0,
    certifications: ['IOCL Approved'],
  },
  {
    id: 'digital_paani',
    name: 'Digital Paani',
    type: 'Service',
    description: 'SaaS platform for wastewater treatment plant monitoring with AI-based process optimization.',
    solutions: ['water_treatment'],
    targetIndustries: ['manufacturing', 'steel', 'healthcare'],
    targetRegions: ['IN'],
    contact: { email: 'hello@digitalpaani.com', phone: '+91-9988776655' },
    website: 'https://digitalpaani.com',
    rating: 4.4,
    certifications: ['NASSCOM Certified'],
  },
  {
    id: 'earth_sync',
    name: 'Earth Sync Analytics',
    type: 'Service',
    description: 'Satellite-powered environmental monitoring for deforestation, land use change, and biodiversity impact.',
    solutions: ['esg_analytics'],
    targetIndustries: ['manufacturing', 'real_estate', 'cement'],
    targetRegions: ['IN', 'US', 'EU', 'AE'],
    contact: { email: 'info@earthsync.ai', phone: '+91-8877665544' },
    website: 'https://earthsync.ai',
    rating: 4.3,
    certifications: ['ISRO Partner'],
  },
  {
    id: 'circular_waste_solutions',
    name: 'Circular Waste Solutions',
    type: 'Service',
    description: 'End-to-end circular economy consulting, waste audits, and zero-waste implementation for enterprises.',
    solutions: ['waste_management'],
    targetIndustries: ['manufacturing', 'real_estate', 'education', 'healthcare'],
    targetRegions: ['IN', 'EU'],
    contact: { email: 'team@circularwaste.com', phone: '+91-7766554433' },
    website: 'https://circularwaste.com',
    rating: 4.5,
    certifications: ['Ellen MacArthur Foundation Network'],
  },
  {
    id: 'apollo_power_systems',
    name: 'Apollo Power Systems',
    type: 'Product',
    description: 'Battery energy storage systems (BESS) for commercial and industrial peak demand management.',
    solutions: ['energy_management'],
    targetIndustries: ['manufacturing', 'it_datacenter', 'real_estate'],
    targetRegions: ['IN', 'US'],
    contact: { email: 'info@apollopower.in', phone: '+91-6655443322' },
    website: 'https://apollopower.in',
    rating: 4.2,
    certifications: ['UL Listed', 'BIS Certified'],
  },
  {
    id: 'outdid_unified',
    name: 'Outdid Unified',
    type: 'Service',
    description: 'Unified sustainability operations platform with multi-site waste, water, and fleet management.',
    solutions: ['waste_management', 'ev_fleet_management'],
    targetIndustries: ['manufacturing', 'logistics', 'automotive', 'real_estate'],
    targetRegions: ['IN', 'US', 'EU'],
    contact: { email: 'hello@outdid.com', phone: '+91-5544332211' },
    website: 'https://outdid.com',
    rating: 4.6,
    certifications: ['ISO 14001', 'ISO 50001'],
  },
];
